sleep.time.second: 5
spring:
  boot.admin.client:
    url: http://localhost:8089
    instance:
      service-base-url: http://localhost:${server.port}/
      prefer-ip: false
  application.name: extractor
  jmx.enabled: true
  cloud:
    function.definition: process
    stream:
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: 192.168.56.4:9092
      bindings:
        applicationMetrics.destination: process-metrics
        process-in-0:
          binder: kafka1
          destination: extraction-requests
          group: extraction
          consumer:
            maxAttempts: 1
        process-out-0:
          binder: kafka1
          destination: conversion-requests

      kafka:
        bindings:
           process-in-0:
             consumer:
               configuration:    
                 isolation.level: read_committed
           process-out-0:
             producer:
               topic.properties:
                 retention.ms: 600000
        binder:
          transaction:
            transaction-id-prefix: extract-
            producer:
              configuration:
                max.in.flight.requests.per.connection: 1
                retries: 1
                acks: all
                enable.idempotence: true
  datasource:
    url: jdbc:h2:mem:sample_mysql_db
    username: root
    password: admin
    driver-class-name: org.h2.Driver
    platform: h2
  h2.console:
    enabled: true
    path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop

server.port: 9998
logging:
  file:
    name: ./logs/${spring.application.name}.log
    max-size: 1MB
    total-size-cap: 3MB
    max-history: 2
    clean-history-on-start: false
  pattern.rolling-file-name: ./logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
  level:
    org.apache.kafka.clients: trace
management:
  metrics:
    export:
      atlas:
        enabled: true
        step: 5s
        uri: "http://localhost:7101/api/v1/publish"
  endpoints:
    health.binders.enabled: true
    enabled-by-default: true
    web:
      exposure.include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: "GET,POST,PUT"
    jmx.exposure.include: '*'
  endpoint:
    health.show-details: always